# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFJH6YkEnKWAB235sO4v33g2RE15birK
"""

import pandas as pd

# Define phishing keywords
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]
#These are words commonly found in phishing emails.
#The script will check if an email contains any of these words.

# Load the dataset (uploaded file)
emails = pd.read_csv("/content/2409001076.csv")

# Check if the 'content' column exists
if 'content' in emails.columns:
    # Apply phishing detection
    emails["is_phishing"] = emails["content"].apply(
        lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
    )
    # Save the processed file
    emails.to_csv("/content/analysed_emails.csv", index=False)
    print("Phishing detection complete. ✅")
else:
    print("Error: The 'content' column is missing from the dataset.")

"""# New Section"""